export const UPDATE_SEARCH_SONG = "UPDATE_SEARCH_SONG";
export const UPDATE_SEARCH_SINGER = "UPDATE_SEARCH_SINGER";
export const UPDATE_SEARCH_ALBUM = "UPDATE_SEARCH_ALBUM";
export const UPDATE_SEARCH_VIDEO = "UPDATE_SEARCH_VIDEO";
export const UPDATE_SEARCH_LYRIC = "UPDATE_SEARCH_LYRIC";
export const UPDATE_SEARCH_SONGSHEET = "UPDATE_SEARCH_SONGSHEET";
export const UPDATE_SEARCH_RADIO = "UPDATE_SEARCH_RADIO";
export const UPDATE_SEARCH_USER = "UPDATE_SEARCH_USER";
