export const CHANGE_CURRENT_SONG = "CHANGE_CURRENT_SONG";
export const ADD_CURRENT_SONG = "ADD_CURRENT_SONG";
export const DELETE_CURRENT_SONG = "DELETE_CURRENT_SONG";
export const CHANGE_CURRENT_INDEX = "CHANGE_CURRENT_INDEX";
export const GET_CURRENT_LYRIC = "GET_CURRENT_LYRIC";
export const SET_LYRIC_INDEX = "SET_LYRIC_INDEX";
export const INCREMENT_SONG_NUM = "INCREMENT_SONG_NUM";

export const wuYa = 1842784921;